### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by fajarwahyu99** [muhrahmatullah/MalariaApp#1]
Ini pakai database tidak ka? Dimana databasenya?
Saya coba implementasi untuk skripsi bisa?

**Comment by muhrahmatullah** [comment]
Untuk aplikasi ini, belum menggunakan database namun kalkulasi dan proses decision making berdasarkan dari dokter(expert). silakan untuk diimplementasi jangan lupa creditnya! terima kasih
